#ifndef MQTT_CLIENT_HPP
#define MQTT_CLIENT_HPP

#include <iostream>
#include <string>
#include <mqtt/async_client.h>

/**
 * @brief CampusSpot MQTT Client Service
 * 
 * Responsible for connecting to the MQTT broker and publishing 
 * edge-processed sensor data in JSON format.
 */
class MqttClient {
private:
    const std::string SERVER_ADDRESS = "tcp://localhost:1883"; // Replace with your MQTT Broker IP
    const std::string CLIENT_ID = "CampusSpot_Node";
    const std::string TOPIC = "campus_spot/nodes/data";
    const int QOS = 1;

    mqtt::async_client client;
    mqtt::connect_options connOpts;

public:
    MqttClient(const std::string& nodeId) 
        : client(SERVER_ADDRESS, nodeId), 
          connOpts() {
        
        connOpts.set_keep_alive_interval(20);
        connOpts.set_clean_session(true);
        connOpts.set_automatic_reconnect(true);
    }

    /**
     * @brief Connect to the MQTT Broker
     * 
     * @return true if connection success or already connected
     */
    bool connect() {
        try {
            if (client.is_connected()) return true;

            std::cout << "[MQTT] Connecting to " << SERVER_ADDRESS << "..." << std::endl;
            client.connect(connOpts)->wait();
            std::cout << "[MQTT] Connection SUCCESS" << std::endl;
            return true;
        } catch (const mqtt::exception& exc) {
            std::cerr << "[MQTT] Connection ERROR: " << exc.what() << std::endl;
            return false;
        }
    }

    /**
     * @brief Publish JSON data to the broker
     * 
     * @param payload JSON string generated by DataAggregator
     */
    void publish(const std::string& payload) {
        try {
            if (!client.is_connected()) {
                connect();
            }

            mqtt::message_ptr pubmsg = mqtt::make_message(TOPIC, payload);
            pubmsg->set_qos(QOS);
            client.publish(pubmsg);
        } catch (const mqtt::exception& exc) {
            std::cerr << "[MQTT] Publish ERROR: " << exc.what() << std::endl;
        }
    }

    bool isConnected() const {
        return client.is_connected();
    }
};

#endif // MQTT_CLIENT_HPP
